services:
  authdb:
    image: authdb
    build:
      context: ./
      dockerfile: DatabaseDockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=abcDEF123#
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433
    expose:
      - 1433

  authservice:
    image: authservice
    build:
      context: ./
      dockerfile: ./ApiDockerfile
    ports:
      - 7227:7227
    expose:
      - 7227
    depends_on:
      - authdb

